# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 14:43
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deposit_percent', models.FloatField()),
                ('credit_percent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='typeMouvementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[("transfert total d'une exploitation", "transfert total d'une exploitation"), ('Transfert de Référence Individuelle avec cession partielle de foncier', 'Transfert de Référence Individuelle avec cession partielle de foncier'), ('Transfert de Référence Individuelle sans foncier', 'Transfert de Référence Individuelle sans foncier'), ('Reprise administrative', 'Reprise administrative'), ('Cession volontaire définitive', 'Cession volontaire définitive'), ('Cession volontaire temporaire', 'Cession volontaire temporaire'), ('Cessation d’activite sans repreneur', 'Cessation d’activite sans repreneur'), ('Attribution de Reference Individuelle par la reserve', 'Attribution de Reference Individuelle par la réserve'), ('Prélèvement sur cessions sans foncier', 'Prélèvement sur cessions sans foncier')], default='', max_length=100)),
                ('informations', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('typemouvementmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='poyosei.typeMouvementModel')),
                ('pacage_cedant', models.CharField(blank=True, max_length=100)),
                ('pacage_repreneur', models.CharField(blank=True, max_length=100)),
                ('année_concerne', models.CharField(blank=True, max_length=4)),
                ('date_demande', models.DateField(blank=True, null=True)),
                ('mouvement_valide', models.BooleanField(default=False)),
                ('date_COSDA_Valide', models.DateField(blank=True, null=True)),
                ('type_reference_individuelle_modifie', models.CharField(blank=True, max_length=100)),
                ('quantite_reference_individuelle_demande', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('quantite_reference_individuelle_accorde', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('taxe', models.FloatField(blank=True, default=0.0)),
            ],
            bases=('poyosei.typemouvementmodel',),
        ),
    ]
