# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0002_mouvement_rule_typemouvementmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacageA', models.CharField(default='', max_length=9)),
                ('planteurs', models.ManyToManyField(to='poyosei.Planteur')),
            ],
        ),
    ]
