# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 14:47
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0003_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='statistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('annee', models.CharField(max_length=4)),
                ('surface_bannane', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surface_jachere', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surface_autre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('surface_totale_utile', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('surface_totale_exploitation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('rendement', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('prodution_exporte', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('production_locale', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('information_diverse', models.TextField()),
                ('surface_propriete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surface_location', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
    ]
