# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 14:48
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0004_statistique'),
    ]

    operations = [
        migrations.CreateModel(
            name='reconstitutionTonnage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pacage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('annee', models.CharField(max_length=4)),
                ('reconstitution_tonnage', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=9)),
                ('justification', models.TextField()),
            ],
        ),
    ]
