# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0006_planteurback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campagne',
            old_name='RID',
            new_name='rid',
        ),
        migrations.RenameField(
            model_name='campagne',
            old_name='RIT',
            new_name='rit',
        ),
    ]
