# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0008_campagne_cloturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='cloturer',
        ),
    ]
