# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0012_auto_20180606_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvement',
            name='quantite_reference_individuelle_accorde2',
        ),
    ]
