# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0017_auto_20180802_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagne',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
