# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 17:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0018_auto_20180802_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouvement',
            name='quantite_reference_individuelle_demande',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='quantite_reference_individuelle_demande',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=10, null=True),
        ),
    ]
