# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0019_auto_20180802_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planteur',
            options={'ordering': ['pacage']},
        ),
        migrations.AlterField(
            model_name='statistique',
            name='pacage',
            field=models.CharField(max_length=9),
        ),
    ]
