# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0020_auto_20180806_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistique',
            options={'ordering': ['pacage']},
        ),
    ]
