# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0021_auto_20180807_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistique',
            old_name='surface_bannane',
            new_name='surface_banane',
        ),
    ]
