# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0022_auto_20180807_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistique',
            old_name='prodution_exporte',
            new_name='production_exporte',
        ),
    ]
