# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0023_auto_20180807_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCampagne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='newTypeMouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_mouvement', models.CharField(max_length=100)),
                ('informations', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='planteurback',
            name='planteur_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalplanteur',
            name='référence_individuelle_définitive',
        ),
        migrations.RemoveField(
            model_name='planteur',
            name='référence_individuelle_définitive',
        ),
        migrations.AlterUniqueTogether(
            name='statistique',
            unique_together=set([('pacage', 'annee')]),
        ),
        migrations.DeleteModel(
            name='PlanteurBack',
        ),
        migrations.AddField(
            model_name='exportcampagne',
            name='planteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poyosei.Planteur'),
        ),
        migrations.AddField(
            model_name='exportcampagne',
            name='statistique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poyosei.statistique'),
        ),
    ]
