# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0024_auto_20180814_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newTypeMouvement',
            new_name='newMouvement',
        ),
    ]
