# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0025_auto_20180814_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportcampagne',
            name='planteur',
        ),
        migrations.RemoveField(
            model_name='exportcampagne',
            name='statistique',
        ),
        migrations.AlterField(
            model_name='statistique',
            name='pacage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poyosei.Planteur'),
        ),
    ]
