# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0026_auto_20180814_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportCampagne',
        ),
    ]
