# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0027_delete_exportcampagne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='pacage',
            field=models.CharField(max_length=9),
        ),
    ]
