# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0028_auto_20180814_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplanteur',
            name='campagne',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='poyosei.Campagne'),
        ),
        migrations.AddField(
            model_name='planteur',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poyosei.Campagne'),
        ),
    ]
