# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0029_auto_20180814_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalplanteur',
            name='campagne',
        ),
        migrations.RemoveField(
            model_name='planteur',
            name='campagne',
        ),
    ]
