# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0030_auto_20180814_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='planteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poyosei.Planteur'),
        ),
    ]
