# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 18:30
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0031_campagne_planteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagne',
            name='planteur',
        ),
        migrations.AlterField(
            model_name='campagne',
            name='rid',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='rit',
            field=models.DecimalField(decimal_places=0, default=Decimal('0.0'), max_digits=20),
        ),
    ]
