# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0032_auto_20180814_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='pacage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='poyosei.Planteur'),
        ),
    ]
