# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0033_auto_20180814_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='pacage',
            field=models.CharField(max_length=9),
        ),
    ]
