# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0035_auto_20180814_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistique',
            name='information_diverse',
            field=models.TextField(blank=True),
        ),
    ]
