# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0037_auto_20180815_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmouvement',
            name='numéro',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='typemouvementmodel',
            name='numéro',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
