# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0038_auto_20180818_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmouvement',
            name='numéro',
        ),
        migrations.RemoveField(
            model_name='typemouvementmodel',
            name='numéro',
        ),
    ]
