# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0040_auto_20180819_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajoutMouvement',
        ),
    ]
