# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0041_delete_ajoutmouvement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajoutMouvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_mouvement', models.CharField(max_length=100)),
                ('informations', models.TextField()),
            ],
        ),
    ]
