# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0044_auto_20180820_0317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajoutMouvement',
        ),
    ]
