# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0046_typemouvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouvement',
            name='type_mouvement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='typemouvementmodel',
            name='type_mouvement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
