# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0050_auto_20180821_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmouvement',
            name='type_reference_individuelle_modifie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_reference_individuelle_modifie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
