# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0051_auto_20180822_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistique',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalmouvement',
            name='type_reference_individuelle_modifie',
            field=models.CharField(choices=[('définitive', 'définitive'), ('temporaire', 'temporaire'), ('autre', 'autre'), ('', '')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mouvement',
            name='type_reference_individuelle_modifie',
            field=models.CharField(choices=[('définitive', 'définitive'), ('temporaire', 'temporaire'), ('autre', 'autre'), ('', '')], default='', max_length=100),
        ),
    ]
