# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-30 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poyosei', '0052_auto_20180828_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
